Repository timaxinc/kcipt, pull requests merged in 2019-10, with the labels that each got.

#15 feat(list-classloader): ClassLoader holding a list of other ClassLoaders
  modules/core/kotlin/com/github/timaxinc/kcipt/classloader/ResourceEnumeration.kt
  modules/core/kotlin/com/github/timaxinc/kcipt/classloader/StackClassloader.kt
Labels: enhancement

#16 feat(blocking-classloader): A ClassLoader with a blacklist able to prevent certain classes from being loaded
  modules/core/kotlin/com/github/timaxinc/kcipt/classloader/BlockingClassloader.kt
  modules/test/test/com/github/timaxinc/kcipt/classloader/BlockingClassloaderTest.kt
Labels: enhancement

#18 feat(ci): Add support for Travis CI
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .travis.yml
  Dockerfile
  README.md
  gradle/wrapper/gradle-wrapper.jar
Labels: enhancement

#20 feat(ci-improved): Improved CI to use dependency caching
  .travis.yml
  Dockerfile
Labels: enhancement

#19 feat(delegate-loader): A classloader with a swappable delegate loader
  .gitignore
  modules/core/kotlin/com/github/timaxinc/kcipt/classloader/DelegateClassloader.kt
  modules/core/kotlin/com/github/timaxinc/kcipt/classloader/URLEnumeration.kt
  modules/test/test/com/github/timaxinc/kcipt/classloader/DelegateClassloaderTest.kt
Labels: enhancement

#26 fix(build-fix): fix gradle build
  build.gradle.kts
  buildSrc/kotlin/Depencecies.kt
  modules/core/build.gradle.kts
  modules/core/kotlin/com/github/timaxinc/kcipt/compile/impl/KotlinJvmCompiledScript.kt
Labels: bug

#27 style(missing-linefeed): apply editor config and add missing blank lines at the end of file
  .travis.yml
  build.gradle.kts
  buildSrc/kotlin/Depencecies.kt
  buildSrc/kotlin/Standard.kt
  buildSrc/kotlin/util/Common.kt
  modules/core/kotlin/com/github/timaxinc/kcipt/CompiledScript.kt
  modules/core/kotlin/com/github/timaxinc/kcipt/Script.kt
  modules/core/kotlin/com/github/timaxinc/kcipt/classloader/BlockingClassloader.kt
  modules/core/kotlin/com/github/timaxinc/kcipt/classloader/DelegateClassloader.kt
  modules/core/kotlin/com/github/timaxinc/kcipt/classloader/StackClassloader.kt
  modules/core/kotlin/com/github/timaxinc/kcipt/classloader/URLEnumeration.kt
  modules/core/kotlin/com/github/timaxinc/kcipt/compile/Compiler.kt
  modules/core/kotlin/com/github/timaxinc/kcipt/compile/CompilerReport.kt
  modules/core/kotlin/com/github/timaxinc/kcipt/compile/impl/KotlinJvmCompiledScript.kt
  modules/core/kotlin/com/github/timaxinc/kcipt/compile/impl/KotlinJvmScriptCompilerReport.kt
  modules/core/kotlin/com/github/timaxinc/kcipt/execute/Executor.kt
  modules/core/kotlin/com/github/timaxinc/kcipt/result/Result.kt
  modules/core/kotlin/com/github/timaxinc/kcipt/source/MutableSource.kt
  modules/core/kotlin/com/github/timaxinc/kcipt/source/Source.kt
  modules/core/kotlin/com/github/timaxinc/kcipt/source/provider/LambdaSource.kt
  modules/core/kotlin/com/github/timaxinc/kcipt/source/provider/MutableLambdaSource.kt
  modules/core/kotlin/com/github/timaxinc/kcipt/source/provider/ResourceContentSource.kt
  modules/lib/kotlin/DefaultScriptContext.kt
  modules/lib/kotlin/ScriptContext.kt
  modules/lib/kotlin/ScriptContextWithInAndOut.kt
  modules/test/test/com/github/timaxinc/kcipt/classloader/BlockingClassloaderTest.kt
  modules/test/test/com/github/timaxinc/kcipt/classloader/DelegateClassloaderTest.kt
  modules/util/kotlin/com/github/timaxinc/kcipt/util/io/Resource.kt
Labels: enhancement

#38 Implement naming convention for dummy classes
  modules/test/test/com/github/timaxinc/kcipt/classloader/BlockingClassloaderTest.kt
  modules/test/test/com/github/timaxinc/kcipt/classloader/DelegateClassloaderTest.kt
Labels: bug

#39 Implement test naming convention
  modules/test/test/com/github/timaxinc/kcipt/classloader/BlockingClassloaderTest.kt
  modules/test/test/com/github/timaxinc/kcipt/classloader/ByteClassloaderTest.kt
  modules/test/test/com/github/timaxinc/kcipt/classloader/DelegateClassloaderTest.kt
Labels: bug

#40 Make URLEnumeration inner class of StackClassloader
  modules/core/kotlin/com/github/timaxinc/kcipt/classloader/StackClassloader.kt
  modules/core/kotlin/com/github/timaxinc/kcipt/classloader/URLEnumeration.kt
Labels: enhancement

#42 feat(doc): add contribution guidelines
  CONTRIBUTING.md
Labels: documentation, enhancement

#46 feat(whitelist-classloader): A classloader with a whitelist
  modules/core/kotlin/com/github/timaxinc/kcipt/classloader/BlacklistClassloader.kt
  modules/core/kotlin/com/github/timaxinc/kcipt/classloader/BlockingClassloader.kt
  modules/core/kotlin/com/github/timaxinc/kcipt/classloader/WhitelistClassloader.kt
  modules/test/test/com/github/timaxinc/kcipt/classloader/BlacklistClassloaderTest.kt
  modules/test/test/com/github/timaxinc/kcipt/classloader/BlockingClassloaderTest.kt
  modules/test/test/com/github/timaxinc/kcipt/classloader/WhitelistClassloaderTest.kt
Labels: enhancement

#48 docs(contributing): update contributing guidelines
  CONTRIBUTING.md
Labels: documentation, enhancement
